### ISSUE TITLE
Split "exporters" into "matchers" and "exporters"

### ISSUE THREAD

**Issue by j-fuentes** [jetstack/preflight#1]
The current "exporters" put together evaluation results and metadata and then render the result in a certain format.

The process of putting together results and metadata should be decoupled from rendering that "pack" into different formats. Here is where the "matcher" + "exporter" pattern comes into place.

As part of this change, the interface for the exporters needs to change to accept a Report struct containing both the result and the metadata, instead of receiving the policy manifest and a result collection as it does now.

**Comment by charlieegan3** [comment]
I'm not familiar with this pattern, but is a matcher that translates result collections and policy manifests into reports ever going to work in more than one way? i.e. will there be more than one matcher?

**Comment by wwwil** [comment]
Ah, I had forgotten about this issue, hence [my comment](https://github.com/jetstack/preflight/pull/63#issuecomment-578777847) on Charlie's PR.

If I understand correctly the idea here is that after Preflight performs evaluation it creates a report from the results and policy manifest, and this report is then used to generate all other forms of output.

**Comment by charlieegan3** [comment]
> and this report is then used to generate all other forms of output.

This makes sense to me - we'd need to change the interface for the exporters though.

**Comment by charlieegan3** [comment]
Closing as this will need to be addressed in a different way with the agent/backend architecture.

/close
