### ISSUE TITLE
Split deployment manifests into groups

### ISSUE THREAD

**Issue by j-fuentes** [jetstack/preflight#19]
Currently, we have just a Kustomize 'base' for Preflight that contains manifests for both RBAC related resources and the CronJob, which means that it all gets applied with one `kubectl apply -k ...`

**The problem**

Typically within an organization, some administrator is going to create the Namespace, ServiceAccount, etc and then another system is going to deploy the workload (the CronJob in this case).

The way these manifests are provided at the moment makes it hard to apply them in two steps.

**Comment by charlieegan3** [comment]
I'm closing this but feel free to reopen. I think that we're going to be starting over for the agent yamls and we can see if this actually comes up as a user request.

We've talked a lot about the 1 yaml install so I think we should focus on that for now.
