### ISSUE TITLE
Expose context information about why a check is failing

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#36]
![Screenshot from 2020-01-08 12-18-49](https://user-images.githubusercontent.com/1774239/71977586-123c5c80-3211-11ea-848f-986cb5368449.png)

This is a screenshot from https://preflight.jetstack.io/

It shows the result of running our basic pod checks. We can see that some pods are missing requests and limits - oh dear.

This is based on the following report: https://github.com/jetstack/preflight/blob/master/examples/reports/pods.json#L7

All that's exposed in the report is the sucess/fail - not the reason.

When using OPA as something that backs a k8s webhook the idiomatic way to do this is to return a message if the rule fails, otherwise return nothing.

In our pod example, I think i'd return the pod name & namespace in a single string, one for each violation.

I guess we might also remove the `success` attribute  and replace it with a `violations` list - if there are violations then it failed?

**Comment by j-fuentes** [comment]
Sounds reasonable.

**Comment by charlieegan3** [comment]
Closing as this as been fixed by the above PRs.
