### ISSUE TITLE
Simplify in-cluster demo deployment

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#37]
At the moment the in-cluster demo outlined here https://github.com/jetstack/preflight/blob/master/docs/installation_manual_in_cluster.md is perhaps a little more complicated than required.

I suggest the following two simplifications:
- use a more simple pod policy 
- use a single GCP iam service account for the pod

**Comment by j-fuentes** [comment]
This does not apply anymore with the new agent based preflight.
