### ISSUE TITLE
Make package lint descend into subdirectories

### ISSUE THREAD

**Issue by wwwil** [jetstack/preflight#48]
When testing packages using the Preflight CLI tool it is possible to test multiple packages together like so:

```
$ preflight package test ./preflight-packages
...
2020/01/20 14:04:59 All packages tests passed :)
```

Here Preflight recursively descends into subdirectories to find packages. However this does not work when linting packages. For example:

```
$ preflight package lint preflight-packages
2020/01/20 14:08:44 Linting package preflight-packages
2020/01/20 14:08:44 Lint: preflight-packages - Unable to read manifest path
2020/01/20 14:08:44 Encountered lint errors
exit status 1
```

The ability to descend into subdirectories should be added to the lint command.

**Comment by charlieegan3** [comment]
The linting of packages has been removed from the public binary and moved to a new cli on the backend. I'm going to close this for now as we have a means of linting and testing all packages via make.
