### ISSUE TITLE
Index report bucket contents

### ISSUE THREAD

**Issue by charlieegan3** [jetstack/preflight#54]
Currently, Preflight will export data to a bucket in the following 'directory' structure:

```
clusterA:
  timestampA:
    packageA.json
    packageB.json
  timestampB:
    ...
clusterB:
  ... 
```

This bucket is queried when the data is loaded for display in the frontend when it is loaded buy the (closed source) preflight backend.

The issues with this format is that all the reports must be listed to find the latest (since we can't order the results from object storage).

Let's change the format to make it possible to find the latest report in constant time.

Goals:
- minimize the complexity in the writes to object storage
- create a structure which helps minimize the complexity in the reads of the same data
- create a structure which allows the latest report for each cluster to be found and loaded quickly
- avoid duplicated data in the bucket
- never delete any data from the bucket

Non goals:
- pagination of results for a single cluster's reports (this can happen at a later date)

**Comment by charlieegan3** [comment]
My proposal when writing a report, we also update a file for a cluster at `index/cluster_name.json` with the following content:

```json
{
  "clusterName": "example",
  "latest_report_timestamp": "string timestamp"
}
```

Where the timestamp is the same as the one most recently used for the writing of the reports.

**Comment by j-fuentes** [comment]
I like the general idea of this proposal.

I would like to suggest some changes to the proposed `index/cluster_name.json` file.

We need to take into account that the "status" of the cluster is not the latest report, but the aggregation of the latest reports for every package. Let's call that a `ReportSet`.

Fortunately, we already have [some types defined](https://github.com/jetstack/preflight/blob/master/api/cluster.go) for the type of information we want to store.

**Comment by charlieegan3** [comment]
I was being pretty casual with my use of the word Report and was using it to mean a ReportSet. Is it possible to have the latest gke report and the latest pod report in a different ReportSet?

**Comment by j-fuentes** [comment]
>  Is it possible to have the latest gke report and the latest pod report in a different ReportSet?

It is possible, but why would you do that? A `ReportSet` groups reports from the same moment, i.e. reports generated in the same preflight run.

> I suppose we could make the index/cluster_name.json file a dump of the ClusterSummary but then it's more of a recent copy than an index.

It is just an index with some (cheap) metadata. It is not a copy of the full report. Note that `ClusterSummary` contains `LatestReportSet` and a `ReportSet.Reports` is just a slice of `ReportSummary`, which is not the full `Report` but just some metadata.

**Comment by charlieegan3** [comment]
> > Is it possible to have the latest gke report and the latest pod report in a different ReportSet?
> 
> It is possible, but why would you do that? 

Not so much want, but I was wondering if that was a requirement we need to cover. E.g. the latest gke failed but the pods one didn't. Sounds like it's not so we're all good!

Ahh I see. Sounds good, I'll see about writing a ClusterSummary in that case.

**Comment by charlieegan3** [comment]
https://github.com/jetstack/preflight/pull/70 closes this
