### ISSUE TITLE
Investigate the best way to authenticate on Azure

### ISSUE THREAD

**Issue by j-fuentes** [jetstack/preflight#56]
Right now, we use a short-lived token for the AKS data-gatherer, and storage account plus secret key for the blob storage (via environment variables).

The short-lived token is a problem for obvious reasons, we need to something that lasts longer.

The storage account and key are fine, but we would like to see if there is something like a credentials file to match what we have for GCS.

**Comment by charlieegan3** [comment]
In an effort to group issues relating to upcoming managed offerings, I'm going to group under https://github.com/jetstack/preflight-private/issues/120
