### ISSUE TITLE
Config file schema

### ISSUE THREAD

**Issue by wwwil** [jetstack/preflight#64]
I feel that it would be better if we defined a Go struct for the Preflight config and un-marshalled YAML into this, rather than using `viper.GetString` throughout the code.

This will make it clearer what the structure of the config should be, and make it clearer when it changes. It also means that the config can be checked more before Preflight actually runs anything.

This would also allow us to add a command to check a config file, if we felt this was useful.

**Comment by AkvileMar** [comment]
it's ready for a review.

**Comment by j-fuentes** [comment]
This is the related PR: https://github.com/jetstack/preflight/pull/82

**Comment by AkvileMar** [comment]
Pull requests are ready to go. It should be merged by the end of today.

**Comment by wwwil** [comment]
Yesterday @j-fuentes PRs #105 and #106 were merged. My PR #107 was merged and planning to finish #104 today.

**Comment by wwwil** [comment]
#104 has been merged, #112 is waiting for review.

#112 tidies up the config loading in `check.go` but does not fully resolve this issue.

**Comment by j-fuentes** [comment]
@wwwil what is missing after #112?

I think it is not worth investing more in this since we are going to transition to the agent soon.

**Comment by wwwil** [comment]
We're still decoding the config from file field by field, rather than unmarshalling directly into a struct.

But I agree that it's not really worth spending more time on this now.
